services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - inception-net
    volumes:
      - website_files:/var/www/html

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    secrets:
      - db
      - user
    restart: always
    networks:
      - inception-net
    volumes:
      - database:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    secrets:
      - db
      - user
    env_file:
      - .env
    restart: always
    networks:
      - inception-net
    volumes:
      - website_files:/var/www/html

# bonus part
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    networks:
      - inception-net

  static:
    build: ./requirements/bonus/static
    container_name: static
    restart: always
    networks:
      - inception-net

secrets:
  db:
    file: ./requirements/secrets/DB.TXT
  user:
    file: ./requirements/secrets/USER.TXT

volumes:
  website_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lgoderne/data/wordpress

  database:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/lgoderne/data/mariadb

  
networks:
  inception-net:
    driver: bridge
